### ISSUE TITLE
Confusion about returned results.

### ISSUE THREAD

**Issue by jmwohl** [SEL-Columbia/mongoose-quadtree#1]
I would expect that if a regular 'within' query returns results, the corresponding compressed within query should also. This is not the case. I'm guessing it might have to do with the threshold and separation params? But it seems like a potential problem.
### e.g.

http://staging.revisit.global/api/v0/facilities.json?within=12.9,6.4,13,6.5

vs

http://staging.revisit.global/api/v0/facilities.json?within=12.9,6.4,13,6.5&compressed

**Comment by Snkz** [comment]
within queries are guaranteed to be a subset of the quadtree queries. It depends on how the within querybox is aligned but usually you'll be getting values back in a larger region then the actual within box.

If you set threshold = 1 and rebuilt the index it should return the exact set of values as within.  Of course though, you'll lose the usefulness of the compression!

**Comment by Snkz** [comment]
this is definitely an issue, ill take a look at somepoint.

can you include the config values in the issue

**Comment by jmwohl** [comment]
Config values:

``` javascript
SiteModel.plugin(quadtree, {
    index: true,
    threshold: 1000,
    seperation: 0.05,
    compress: true,
    collectionName: 'facilities'
});
```

**Comment by Snkz** [comment]
sooo, I think I may of found the issue. I must be screwing up and reversing the bound calculation somewhere in the code cause the query http://staging.revisit.global/api/v0/facilities.json?within=13,6.5,12.9,6.4&compressed returns correct results. Also I restarted Revisit's staging server and it seems to be working fine. I think changing the values passed into the query in controller/site.js of revisit will solve your issue but it would be better if the quadtree code was corrected.

**Comment by Snkz** [comment]
also the query http://staging.revisit.global/api/v0/facilities.json?within=12.9,6.4,12.9,6.4&compressed returns results in the ride node as well... pretty sure its just an ordering thing

**Comment by Snkz** [comment]
Let me know if this solves the issue, confirm all facilities that revisit normally returns are contained in the result.

**Comment by jmwohl** [comment]
Hmm, unfortunately I don't think this is the issue, unless I'm misunderstanding what you mean. As a quick test I tried a few of the other queries I still had open in browser windows:

#### All of Nigeria:

Returns correct results:
http://staging.revisit.global/api/v0/facilities.json?within=2.6769,4.1042,14.678,13.8856

No results:
http://staging.revisit.global/api/v0/facilities.json?within=2.6769,4.1042,14.678,13.8856&compressed

Reversed coordinates, still no results:
http://staging.revisit.global/api/v0/facilities.json?within=14.678,13.8856,2.6769,4.1042&compressed

#### Entire world:

Returns correct results:
http://staging.revisit.global/api/v0/facilities.json?within=-85,-180,85,180

No results:
http://staging.revisit.global/api/v0/facilities.json?within=-85,-180,85,180&compressed

Reversed coordinates, still no results:
http://staging.revisit.global/api/v0/facilities.json?within=85,180,-85,-180&compressed

**Comment by Snkz** [comment]
Nigeria: http://staging.revisit.global/api/v0/facilities.json?within=14.678,4.1042,2.6769,13.8856
World: http://staging.revisit.global/api/v0/facilities.json?within=85,-180,-85,180&compressed

I must of screwed up east/west?

Although the count seems to be maxed out ... that could be a concidence.

Edit: No I think its right: http://staging.revisit.global/api/v0/facilities.json?within=13,6.4,12.9,6.5&compressed

**Comment by jmwohl** [comment]
Alright, cool! Yeah, makes sense that the total count is the same since all facilities are in Nigeria at the moment. I'll look at it today and see if I can find where they are swapped.

Thanks for helping with this!

**Comment by Snkz** [comment]
If I were to guess, it would be in lib/utils.js. Specifically crossesNode.

No prob!

**Comment by jmwohl** [comment]
Ok, got it. Turns out this isn't an issue with the quadtree plugin! 

A) I'm an idiot and didn't pay attention to the ordering of the coordinates I was putting in to the within query, and was blindly copying them from [this bounding box map](http://boundingbox.klokantech.com/) output. So instead of **n,w,s,e** I was using **w,s,e,n**. 

B) The curious thing that really confused me is that the Revisit API seems to be flexible in the coordinate order for the within query bounding box. This is probably because mongo is flexible. But it was confusing since the bounding box with the wrong coordinates specified still returned the expected result! Until the **compressed** flag was added.

Anyway, as long as we actually follow the damn Revisit API (whoops.), it seems to work fine. Sorry for wasting your time, and thanks again!

Jon
